## Database settings
oaccDb:
  # the name of the JDBC driver
  driverClass: org.hsqldb.jdbc.JDBCDriver

  # the username
  user: oaccuser

  # the password
  password: oaccpwd

  # the JDBC URL
  url: jdbc:hsqldb:mem:oaccdb

  #the sql query to run when validating a conections liveness
  validationQuery: "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SYSTEM_TABLES"


## OACC settings
oacc:
  schemaName: OACC
  sqlProfile: HSQLDB_2_3_NON_RECURSIVE

logging:
  level: INFO
  loggers:
    com.bhattacherjee.app.delegation: DEBUG
