--liquibase formatted sql

--changeset properties-db:propertiesdb-1.1 stripComments:true

--------------------------------------------------------
-- Copyright 2009-2016, Acciente LLC
--
-- Acciente LLC licenses this file to you under the
-- Apache License, Version 2.0 (the "License"); you
-- may not use this file except in compliance with the
-- License. You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in
-- writing, software distributed under the License is
-- distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
-- OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing
-- permissions and limitations under the License.
--------------------------------------------------------

-- ----------------------------------------------------------------------
-- Sequences
-- ----------------------------------------------------------------------

CREATE SEQUENCE PROPERTIES.PropertyId AS BIGINT START WITH 1 INCREMENT BY 1;

-- ----------------------------------------------------------------------
-- Tables
-- ----------------------------------------------------------------------

CREATE TABLE PROPERTIES.User (
    Email VARCHAR(128)  NOT NULL,
    CONSTRAINT PK_User PRIMARY KEY (Email)
);

CREATE INDEX IX_User_Email ON PROPERTIES.User (Email);

CREATE TABLE PROPERTIES.Property (
    Id BIGINT GENERATED BY DEFAULT AS SEQUENCE PROPERTIES.PropertyId NOT NULL,
    Title VARCHAR(128)  NOT NULL,
    PostalCd SMALLINT  NOT NULL,
    CONSTRAINT PK_Property PRIMARY KEY (Id)
);

CREATE INDEX IX_Property_Id ON PROPERTIES.Property (Id);
CREATE INDEX IX_Property_PostalCd ON PROPERTIES.Property (PostalCd);